## **PyTorch Fundamentals**

---



Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Introduction to Tensors

### What is tensors?
Tensors are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors. In fact tensors are merely a generalisation of scalars and vectors; a scalar is a zero rank tensor, and a vector is a first rank tensor.

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.Tensor([7,7])
vector

tensor([7., 7.])

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
tensor = torch.tensor([[12,2,2]])
tensor

tensor([[12,  2,  2]])

In [11]:
tensor.ndim

2

In [12]:
tensor.shape

torch.Size([1, 3])

In [13]:
tensor[0]

tensor([12,  2,  2])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [14]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3255, 0.7736, 0.1392, 0.2362],
        [0.4191, 0.7644, 0.4489, 0.2076],
        [0.2484, 0.8555, 0.1818, 0.5220]])

In [15]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor

tensor([[[0.9985, 0.1640, 0.9526,  ..., 0.7536, 0.2141, 0.8246],
         [0.8826, 0.6109, 0.5644,  ..., 0.1878, 0.2276, 0.6763],
         [0.3979, 0.2325, 0.3457,  ..., 0.1660, 0.3481, 0.4582],
         ...,
         [0.8479, 0.8993, 0.2183,  ..., 0.6006, 0.2325, 0.9427],
         [0.4191, 0.9384, 0.6589,  ..., 0.7471, 0.4956, 0.7141],
         [0.9428, 0.5690, 0.1850,  ..., 0.6085, 0.1994, 0.7531]],

        [[0.2604, 0.1103, 0.7675,  ..., 0.8782, 0.2052, 0.6348],
         [0.1445, 0.5985, 0.9547,  ..., 0.3340, 0.9931, 0.7155],
         [0.9597, 0.4126, 0.6521,  ..., 0.6532, 0.1806, 0.1199],
         ...,
         [0.6135, 0.9212, 0.5849,  ..., 0.1051, 0.5141, 0.1410],
         [0.9529, 0.4886, 0.4463,  ..., 0.7482, 0.2774, 0.2595],
         [0.6129, 0.8223, 0.0231,  ..., 0.3002, 0.5219, 0.0540]],

        [[0.9201, 0.4501, 0.7965,  ..., 0.1409, 0.9315, 0.2218],
         [0.5226, 0.0881, 0.8827,  ..., 0.9082, 0.2191, 0.6934],
         [0.4715, 0.9480, 0.6508,  ..., 0.3983, 0.3144, 0.

### Zeros and ones

In [16]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

In [19]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [20]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes 

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0])
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [28]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [29]:
int_32_tensor = torch.tensor([3,6,9],dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6518, 0.4281, 0.0058, 0.5887],
        [0.6229, 0.3005, 0.5927, 0.3391],
        [0.4166, 0.7747, 0.5849, 0.7579]])

In [32]:
print(random_tensor)
print(f"Datatype of tensor :  {random_tensor.dtype}")
print(f"shape of tensor :  {random_tensor.shape}")
print(f"device of tensor :  {random_tensor.device}")

tensor([[0.6518, 0.4281, 0.0058, 0.5887],
        [0.6229, 0.3005, 0.5927, 0.3391],
        [0.4166, 0.7747, 0.5849, 0.7579]])
Datatype of tensor :  torch.float32
shape of tensor :  torch.Size([3, 4])
device of tensor :  cpu


### Manipulating Tensors (tensor operations)

Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [33]:
tensor = torch.tensor([3,2,5])
tensor + 10

tensor([13, 12, 15])

In [34]:
tensor * 10

tensor([30, 20, 50])

In [35]:
tensor - 10

tensor([-7, -8, -5])

In [36]:
torch.mul(tensor,10)

tensor([30, 20, 50])

In [37]:
torch.add(tensor, 10)

tensor([13, 12, 15])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [38]:
print(tensor,"*",tensor)

tensor([3, 2, 5]) * tensor([3, 2, 5])


In [39]:
torch.matmul(tensor,tensor)

tensor(38)

In [40]:
tensor

tensor([3, 2, 5])

In [41]:
%%time
3*3+2*2+5*5

CPU times: user 10 µs, sys: 1e+03 ns, total: 11 µs
Wall time: 15.3 µs


38

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(38)
CPU times: user 869 µs, sys: 0 ns, total: 869 µs
Wall time: 879 µs


In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 35 µs, sys: 0 ns, total: 35 µs
Wall time: 37.9 µs


tensor(38)

### One of the most common errors in deep learning: shape errors

In [44]:
# Shapes for matrix multiplication 
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [45]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [47]:
tensor_A.shape, tensor_A.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [48]:
print(f"Original shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape} ")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Outout:#n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"#nOutput shape : {output.shape}")

Original shapes : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3]) 
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Outout:#n
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
#nOutput shape : torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [49]:
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [50]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [51]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [52]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [53]:
torch.sum(x) , x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [54]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [55]:
x.argmin()

tensor(0)

In [56]:
x[0]

tensor(1)

In [57]:
x.argmax()

tensor(9)

In [58]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [59]:
import torch
x= torch.arange(1.0,10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
#x and z are sharing the same memory
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [63]:
x_stacked = torch.stack([x,x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [64]:
x_stacked = torch.stack([x,x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [65]:
x_stacked = torch.stack([x,x,x,x,x],dim=2)
x_stacked

IndexError: ignored

In [66]:
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"New tensor : {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])
New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [94]:
print(f"Previos tensor : {x_squeezed}")
print(f"Previos shape : {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"New tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previos tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previos shape : torch.Size([9])
New tensor : tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape : torch.Size([9, 1])


In [68]:
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)

print(f"previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}")

previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [69]:
x_original[0,0,0] = 878787
x_original[0,0,0], x_permuted[0,0,0,]


(tensor(878787.), tensor(878787.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [70]:
import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [71]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
x[0][0]

tensor([1, 2, 3])

In [73]:
x[0,0]

tensor([1, 2, 3])

In [74]:
x[:,0]

tensor([[1, 2, 3]])

In [75]:
x[:,:,1]

tensor([[2, 5, 8]])

In [76]:
x[:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [77]:
x[0,:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library. 

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()` 

In [79]:
import torch
import numpy as np

array =np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [80]:
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [81]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [82]:
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [83]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B == random_tensor_A)

tensor([[0.1743, 0.3767, 0.3118, 0.9900],
        [0.5353, 0.0533, 0.3267, 0.3505],
        [0.3118, 0.7922, 0.1851, 0.1793]])
tensor([[0.8573, 0.3460, 0.6728, 0.4303],
        [0.7994, 0.9388, 0.4613, 0.9490],
        [0.4696, 0.3238, 0.1530, 0.1253]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [84]:
import torch

RANDOM_SEED = 100
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)


print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

 ## Running tensors and PyTorch objects on the GPUs (and making faster computations)

 GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/ 

In [85]:
!nvidia-smi

Wed Jan 18 20:13:22 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    27W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [86]:
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [87]:
device = "cuda"  if torch.cuda.is_available() else "cpu"
device

'cuda'

In [88]:
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [89]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [90]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [91]:
# If tensor is on GPU, can't transform it to NumPy

tensor_on_gpu.numpy()

TypeError: ignored

In [92]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [93]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')